import "../styles/globals.css";
import "react-toastify/dist/ReactToastify.css";
import type { AppProps } from "next/app";
import { ToastContainer } from "react-toastify";
import { SWRConfig } from "swr";
import axiosClient from "../api-client/axios-client";
import Head from "next/head";
import "mapbox-gl/dist/mapbox-gl.css";
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <SWRConfig
      value={{
        fetcher: async (url) => await axiosClient.get(url),
        shouldRetryOnError: false,
      }}
    >
      <Head>
        <title>akinha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      <ToastContainer />
    </SWRConfig>
  );
}
export default MyApp;
