import type { NextPage } from "next";
import Head from "next/head";
import { motion } from "framer-motion";
import ReactMapGL from "react-map-gl";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        className=" w-screen h-screen overflow-hidden"
        initial={{ scale: 0.1, opacity: 0 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 2 }}
      >
        <ReactMapGL
          initialViewState={{
            latitude: 21.0244246,
            longitude: 105.7938072,
            zoom: 16,
          }}
          mapStyle="mapbox://styles/mapbox/streets-v10"
          mapboxAccessToken="pk.eyJ1IjoiY2Z0bmloIiwiYSI6ImNsNjdzZnB5bzNudTQzYm1wa21mbXo2emEifQ.SDqggkiy2bskCxRu4dYYkA"
        ></ReactMapGL>
      </motion.div>
    </div>
  );
};

export default Home;
